swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
          
          
  /user/accounts/{accountId}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Get All Transactions of an account
      description: API for fetching all transactions of a user
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: accountId
          type: integer
          required: true
          description: Numeric ID of the account to get
      produces:
        - application/json
      responses:
        '200':
          description: User account number {id} transactions successully
          schema:
            $ref: '#/definitions/ApiAllTransactionsResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
          
    post:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Post One Transaction of an account
      description: API for posting one transaction of a user
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: body
          name: body
          description: Post new user transaction attributes
          required: true
          schema:
            $ref: '#/definitions/PostTransaction'
        - in: path
          name: accountId
          type: integer
          required: true
          description: Numeric ID of the account to post transaction in
      produces:
        - application/json
      responses:
        '200':
          description: User posting new transaction successully
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
          
  /user/accounts/{accountId}/transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Get One Transaction of an account
      description: API for fetching one transactions of a user
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: accountId
          type: integer
          required: true
          description: Numeric ID of the account to get
        - in: path
          name: transactionId
          type: integer
          required: true
          description: Numeric ID of the transaction to get
      produces:
        - application/json
      responses:
        '200':
          description: User fetching transaction {id} from account number {id}  successully
          schema:
            $ref: '#/definitions/ApiTransactionResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
          
    put:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Put one transaction of an account
      description: API for modify one transaction of a user
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: body
          name: body
          description: Update user transaction attributes
          required: true
          schema:
            $ref: '#/definitions/PostTransaction'
        - in: path
          name: accountId
          type: integer
          required: true
          description: Numeric ID of the account to put transaction in
        - in: path
          name: transactionId
          type: integer
          required: true
          description: Numeric ID of the transaction to get
      produces:
        - application/json
      responses:
        '200':
          description: User modify transaction successully
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
          
    delete:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Put one transaction of an account
      description: API for modify one transaction of a user
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: body
          name: body
          description: Update user transaction attributes
          required: true
          schema:
            $ref: '#/definitions/PostTransaction'
        - in: path
          name: accountId
          type: integer
          required: true
          description: Numeric ID of the account to put transaction in
        - in: path
          name: transactionId
          type: integer
          required: true
          description: Numeric ID of the transaction to get
      produces:
        - application/json
      responses:
        '200':
          description: User delete transaction successully
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  
  
          
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  
  ApiTransactionResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          description:
            type: string
          date:
            type: string
          amount:
            type: integer
          transactionType:
            type: string
          notes:
            type: string
            
  ApiAllTransactionsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          transactions:
            type: object
            properties:
              id:
                type: string
              description:
                type: string
              date:
                type: string
              amount:
                type: integer
              transactionType:
                type: string
              notes:
                type: string          
            
  PostTransaction:
    properties:
      id:
        type: string
        description: user email
      description:
        type: string
        description: user email
      date:
        type: string
        description: user password
      amount:
        type: string
        description: user password
      transactionType:
        type: string
        description: user password
      notes:
        type: string
        description: user password
            
            
